-- =====================================================================
-- 在线音乐分享系统 — 物理设计 / 建表脚本 (01_schema.sql)
-- DBMS   : PostgreSQL 14+ (建议 16)
-- 编码   : UTF8
-- 主键   : BIGINT GENERATED BY DEFAULT AS IDENTITY (允许测试数据显式写入)
-- 约束   : 使用 DB 级 CHECK / UNIQUE / FOREIGN KEY 保证完整性
-- 删除   : 主体软删除(is_deleted);外键 ON DELETE CASCADE 作物理清理兜底
-- =====================================================================

-- 子串模糊搜索(LIKE '%x%')所需的三元组索引扩展,索引脚本中使用
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- --------------------------------------------------------------------
-- R1 用户表  (user 为 PG 保留字,故命名 app_user)
-- --------------------------------------------------------------------
CREATE TABLE app_user (
    uid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,                 -- 登录名
    password    VARCHAR(100) NOT NULL,                        -- bcrypt 密文
    nickname    VARCHAR(50)  NOT NULL,                        -- 昵称
    email       VARCHAR(100) UNIQUE,                          -- 邮箱,可空
    avatar      VARCHAR(255),                                 -- 头像路径
    role        SMALLINT     NOT NULL DEFAULT 0 CHECK (role IN (0,1,2)),   -- 0普通/1上传者/2管理员
    status      SMALLINT     NOT NULL DEFAULT 0 CHECK (status IN (0,1)),   -- 0正常/1封禁
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,          -- 软删除标记
    reg_time    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE  app_user IS '用户表:普通用户/上传者/管理员三种角色';

-- --------------------------------------------------------------------
-- R2 专辑表
-- --------------------------------------------------------------------
CREATE TABLE album (
    aid          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_name   VARCHAR(100) NOT NULL,                       -- 专辑名
    cover        VARCHAR(255),                                -- 封面路径
    release_date DATE,                                        -- 发行日期
    introduction TEXT,                                        -- 简介
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,         -- 是否单曲缺省专辑
    creator_uid  BIGINT       NOT NULL
                 REFERENCES app_user(uid) ON DELETE CASCADE,  -- 创建者
    is_deleted   BOOLEAN      NOT NULL DEFAULT FALSE          -- 软删除标记(与 song 对称)
);
COMMENT ON TABLE album IS '专辑表;is_default=true 表示为单曲自动生成的独立缺省专辑';

-- --------------------------------------------------------------------
-- R3 音乐表
-- --------------------------------------------------------------------
CREATE TABLE song (
    sid          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(150) NOT NULL,                       -- 标题
    cover        VARCHAR(255),                                -- 封面路径
    duration     INT          CHECK (duration IS NULL OR duration > 0),  -- 时长(秒)
    lyric        TEXT,                                        -- 歌词
    audio_path   VARCHAR(255) NOT NULL,                       -- 音频文件路径
    play_count   BIGINT       NOT NULL DEFAULT 0 CHECK (play_count >= 0), -- 冗余总点唱数
    album_aid    BIGINT       NOT NULL                        -- 所属专辑(决策①:非空)
                 REFERENCES album(aid) ON DELETE CASCADE,
    uploader_uid BIGINT       NOT NULL
                 REFERENCES app_user(uid) ON DELETE CASCADE,  -- 上传者
    audit_status SMALLINT     NOT NULL DEFAULT 0 CHECK (audit_status IN (0,1,2)), -- 0待审/1通过/2驳回
    audit_remark VARCHAR(255),                                -- 驳回理由
    is_deleted   BOOLEAN      NOT NULL DEFAULT FALSE,         -- 软删除标记
    create_time  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE song IS '音乐表:必属一个专辑,含审核状态与软删除';

-- --------------------------------------------------------------------
-- R4 点唱记录表 (排行榜与统计的真相源)
-- --------------------------------------------------------------------
CREATE TABLE play_record (
    pid       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid       BIGINT      NOT NULL REFERENCES app_user(uid) ON DELETE CASCADE,
    sid       BIGINT      NOT NULL REFERENCES song(sid)     ON DELETE CASCADE,
    play_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP   -- 排行榜核心字段
);
COMMENT ON TABLE play_record IS '点唱记录:每次点唱一行,日/周榜按 play_time 聚合的数据来源';

-- --------------------------------------------------------------------
-- R5 评论表 (评论无评分;parent_cid 自引用支持楼中楼)
-- --------------------------------------------------------------------
CREATE TABLE comment (
    cid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         BIGINT      NOT NULL REFERENCES app_user(uid) ON DELETE CASCADE,
    sid         BIGINT      NOT NULL REFERENCES song(sid)     ON DELETE CASCADE,
    content     TEXT        NOT NULL,
    like_count  INT         NOT NULL DEFAULT 0 CHECK (like_count >= 0), -- 冗余点赞数
    parent_cid  BIGINT      REFERENCES comment(cid) ON DELETE CASCADE,  -- 父评论,可空
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE comment IS '评论表:与评分解耦,可多次评论;parent_cid 实现回复';

-- --------------------------------------------------------------------
-- R6 评分表 (与评论独立;一人对一首歌仅一次)
-- --------------------------------------------------------------------
CREATE TABLE rating (
    rid       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid       BIGINT      NOT NULL REFERENCES app_user(uid) ON DELETE CASCADE,
    sid       BIGINT      NOT NULL REFERENCES song(sid)     ON DELETE CASCADE,
    score     SMALLINT    NOT NULL CHECK (score BETWEEN 1 AND 5),
    rate_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rating_user_song UNIQUE (uid, sid)          -- 决策③:一人一首仅一次
);
COMMENT ON TABLE rating IS '评分表:1~5 分,(uid,sid) 唯一,与评论解耦';

-- --------------------------------------------------------------------
-- R7 歌单表
-- --------------------------------------------------------------------
CREATE TABLE playlist (
    plid          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid           BIGINT      NOT NULL REFERENCES app_user(uid) ON DELETE CASCADE,
    playlist_name VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    cover         VARCHAR(255),
    is_public     BOOLEAN     NOT NULL DEFAULT TRUE,           -- 公开/私密
    create_time   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE playlist IS '歌单表:用户私有音乐集合,可设公开/私密';

-- --------------------------------------------------------------------
-- R8 歌单详情表 (歌单 n:m 音乐)
-- --------------------------------------------------------------------
CREATE TABLE playlist_detail (
    pdid     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plid     BIGINT      NOT NULL REFERENCES playlist(plid) ON DELETE CASCADE,
    sid      BIGINT      NOT NULL REFERENCES song(sid)      ON DELETE CASCADE,
    add_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pldetail_pl_song UNIQUE (plid, sid)         -- 同一歌单不重复加同一首
);
COMMENT ON TABLE playlist_detail IS '歌单详情:歌单与音乐的多对多联系';

-- --------------------------------------------------------------------
-- R9 收藏表 (用户 n:m 音乐)
-- --------------------------------------------------------------------
CREATE TABLE favorite (
    fid      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid      BIGINT      NOT NULL REFERENCES app_user(uid) ON DELETE CASCADE,
    sid      BIGINT      NOT NULL REFERENCES song(sid)     ON DELETE CASCADE,
    fav_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_favorite_user_song UNIQUE (uid, sid)        -- 不可重复收藏
);
COMMENT ON TABLE favorite IS '收藏表:用户收藏的音乐,(uid,sid) 唯一';

-- --------------------------------------------------------------------
-- R10 评论点赞表 (用户 n:m 评论)
--   与 favorite/rating 同构:uid + 目标 + UNIQUE 防重。
--   点赞数实时 COUNT(*) 统计,comment.like_count 冗余字段闲置不用。
--   删评论时 ON DELETE CASCADE 自动清理其点赞记录。
-- --------------------------------------------------------------------
CREATE TABLE comment_like (
    clid      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid       BIGINT      NOT NULL REFERENCES app_user(uid) ON DELETE CASCADE,
    cid       BIGINT      NOT NULL REFERENCES comment(cid)  ON DELETE CASCADE,
    like_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_comment_like_user_comment UNIQUE (uid, cid)  -- 一人对一条评论仅一次
);
COMMENT ON TABLE comment_like IS '评论点赞表:用户点赞的评论,(uid,cid) 唯一,防重复点赞';


